language: node_js
node_js:
  - "stable"
  - 8
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - rabbitmq-server
      - wget

before_install:
  - cd $(sudo rabbitmqctl environment | sed -n 's/.*plugins_dir\s*,\s*"\([^"]*\)".*/\1/p');
    sudo wget -q https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.8.0/rabbitmq_delayed_message_exchange-3.8.0.ez;
    echo "=========================";
    echo "Rabbit plugins directory:";
    echo "=========================";
    pwd;
    ls -la
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo rabbitmq-plugins enable rabbitmq_delayed_message_exchange

script:
  - yarn test
