language: node_js
node_js:
  - "stable"
  - 8
cache:
  directories:
    - "node_modules"
addons:
  apt:
    packages:
      - rabbitmq-server
script:
  - sudo rabbitmq-plugins enable rabbitmq_management
  #- sleep 2 # wait for management plugin to properly start up
  - yarn test
